compile:
	@g++ CourseWork.cpp lib/words.cpp -o game.out >> /dev/null

compile-oop:
	@g++ CourseWorkOOP.cpp lib/words.cpp -o game-oop.out >> /dev/null

run:
	@./game.out

run-oop:
	@./game-oop.out

game: compile run

game-oop: compile-oop run-oop
